apiVersion: batch/v1
kind: Job
metadata:
  name: busybox-job
spec:
  completions: 3
  parallelism: 2
  backoffLimit: 4
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sleep", "25"]
      restartPolicy: OnFailure