version: '3.4'

services:
  front-end:
    image: vote-app:v1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - "db"
  db:
    image: redis:alpine
    hostname: redis-db
    container_name: redis-db
    ports:
      - "6379:6379"