apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-mi
  namespace: podidentity
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: "<<Key vault name>>"
    objects:  |
      array:
        - |
          objectName: connectionString
          objectType: secret
    tenantId: "<<Tenant ID>>"