apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "echo UserName: $user, Password: $password" ]
      envFrom:
      - secretRef:
          name: k8ssecret
  restartPolicy: Never