apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    userAssignedIdentityID: "707e9049-840e-40d6-bf70-d364d086f918"
    keyvaultName: "nc-aks-vault"
    objects:  |
      array:
        - |
          objectName: connectionString
          objectType: secret
    resourceGroup: "aks-training"
    subscriptionId: "3ae9274d-2199-45b5-9e52-21c25a39a8ce"
    tenantId: "92dcc73c-c110-49f6-acec-19a7cf8fb5f4"