apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname-mi
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    userAssignedIdentityID: "<<Client ID of the managed Identity>>"
    keyvaultName: "<<Your Key Vault name>>"
    objects:  |
      array:
        - |
          objectName: connectionString
          objectType: secret
    resourceGroup: "aks-training"
    subscriptionId: "<<your subscription Id>>"
    tenantId: "<<Your tenant id>>"